ARG UBUNTU_VERSION=24.04
ARG CUDA_VERSION=12.6.3
ARG BASE_CUDA_DEVEL_CONTAINER=nvidia/cuda:${CUDA_VERSION}-devel-ubuntu${UBUNTU_VERSION}
ARG BASE_CUDA_RUNTIME_CONTAINER=nvidia/cuda:${CUDA_VERSION}-runtime-ubuntu${UBUNTU_VERSION}

FROM ${BASE_CUDA_DEVEL_CONTAINER} AS builder
WORKDIR /app

ARG LLAMACPP_REPO="https://github.com/ggerganov/llama.cpp.git"
# It may be name of branch, tag or commit hash
ARG LLAMACPP_VERSION="master"

# To get latest tag use this:
# git -c 'versionsort.suffix=-' ls-remote --tags --sort='v:refname' \
#    "https://github.com/ggerganov/llama.cpp.git" 'b*' | \
#    tail --lines=1 | cut --delimiter='/' --fields=3
# For details see here: https://stackoverflow.com/questions/8932389/git-shallow-clone-to-specific-tag)

# Install dependencies
RUN set -xe \
 && apt update -q \
 && apt install -fyq bash wget git cmake make g++ curl libcurl4-openssl-dev \
 && apt clean

# Clone repo
RUN set -xe \
 && git clone --branch "$LLAMACPP_VERSION" --depth 1 "$LLAMACPP_REPO"

# Build binaries
WORKDIR /app/llama.cpp
RUN ln -s /usr/local/cuda/lib64/stubs/libcuda.so /usr/local/cuda/lib64/stubs/libcuda.so.1
RUN set -xe \
 && export LD_LIBRARY_PATH=/usr/local/cuda/lib64/stubs/:$LD_LIBRARY_PATH \
 && cmake -B build -DGGML_CUDA=ON -DGGML_RPC=ON -DCMAKE_BUILD_RPATH_USE_ORIGIN=ON \
 && cmake --build build --config Release -j$(nproc)


FROM ${BASE_CUDA_RUNTIME_CONTAINER}
WORKDIR /app

# Install basic dependencies
RUN set -xe \
 && apt update -q \
 && apt install -fyq libgomp1 curl \
 && apt clean

# Create folders
RUN set -xe \
 && mkdir -pv /app/models

# Copy compiled tools. Staged into /app/bin-src first because the RPC server
# binary was renamed rpc-server -> ggml-rpc-server upstream at some point; this
# handles EITHER name (old or new tags) so the same Dockerfile builds any
# LLAMACPP_VERSION without edits.
COPY --from=builder /app/llama.cpp/build/bin/ /app/bin-src/
RUN set -xe \
 && cp /app/bin-src/*.so /usr/lib/x86_64-linux-gnu/ \
 && cp /app/bin-src/llama-cli /app/bin-src/llama-embedding /app/bin-src/llama-server . \
 && if [ -f /app/bin-src/ggml-rpc-server ]; then cp /app/bin-src/ggml-rpc-server ./rpc-server; \
    else cp /app/bin-src/rpc-server ./rpc-server; fi \
 && rm -rf /app/bin-src

# The dynamic linker looks for the versioned soname (libxxx.so.0); the build only
# produces the unversioned libxxx.so. Symlink every lib generically so new shared
# libs added upstream don't require updating this list.
RUN set -xe \
 && cd /usr/lib/x86_64-linux-gnu \
 && for lib in *.so; do [ -e "$lib.0" ] || ln -s "$lib" "$lib.0"; done

# Init entrypoint
ADD entrypoint.sh .
ENTRYPOINT ["/app/entrypoint.sh"]
